### ISSUE TITLE
🚀 Feature: Upgrade this site new version of sveltekit

### ISSUE THREAD

**Issue by FarhanAliRaza** [appwrite/hacktoberfest#34]
### 🔖 Feature description

As sveltekit is now in the countdown to the stable release. They promise no more breaking changes. 
Sveltekit should be upgraded to the new version.
There are some breaking changes.
I want to it for hacktoberfest 22. 
should i do it? @wess @eldadfux @stnguyen90 @TorstenDittmann @tessamero 

### 🎤 Pitch

As sveltekit is now in the countdown to the stable release. They promise no more breaking changes. 
Sveltekit should be upgraded to the new version.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@FarhanAliRaza We love contributions, but we suggest you try and submit more meaningful PRs by exploring hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/). If you have any problems or need help, please join our [Discord community](https://appwrite.io/discord) and use the `#hacktoberfest` channel.
