### ISSUE TITLE
📚 Documentation:  npm i && npm run dev fails to run the project on localhost (mandatory to have yarn installed)

### ISSUE THREAD

**Issue by KENILSHAHH** [appwrite/hacktoberfest#53]
### 💭 Description

Since the 'dev' script include yarn commands, its mandatory to have both yarn as well as npm package installed to run the code on local machine
![image](https://user-images.githubusercontent.com/93181200/197504392-5bb91704-eb49-4607-a952-9c7fc9e3b4c3.png)

**Will update the readme file accordingly**

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by KENILSHAHH** [comment]
Please assign this issue to me so that i can work upon it quickly

**Comment by stnguyen90** [comment]
@KENILSHAHH, it's okay, we'll take care of this. If you're still looking to contribute for Hacktoberfest please try exploring hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/). If you have any problems or need help, please join our [Discord community](https://appwrite.io/discord) and use the `#hacktoberfest` channel.
