### ISSUE TITLE
📚 Documentation: Update Banner in `README.md`

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/hacktoberfest#63]
### 💭 Description

The landing page image banner / showcase uses old UI & Logo in the `README.md`.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ArslanYM** [comment]
Can I work on this?

**Comment by Haimantika** [comment]
> ### 💭 Description
> The landing page image banner / showcase uses old UI & Logo in the `README.md`.
> 
> ### 👀 Have you spent some time to check if this issue has been raised before?
> * [x]  I checked and didn't find similar issue
> 
> ### 🏢 Have you read the Code of Conduct?
> * [x]  I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

Can you add a screenshot?

**Comment by Haimantika** [comment]
> ### 💭 Description
> The landing page image banner / showcase uses old UI & Logo in the `README.md`.
> 
> ### 👀 Have you spent some time to check if this issue has been raised before?
> * [x]  I checked and didn't find similar issue
> 
> ### 🏢 Have you read the Code of Conduct?
> * [x]  I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

Hi, this repo is for our old website. We are no longer using it.

**Comment by ItzNotABug** [comment]
@Haimantika Ohh I saw a fresh PR by Steven so I thought this is still used.
Let me know if I should close this.

**Comment by mschandana16** [comment]
@Haimantika, can you please assign this issue to me? I would want to update the landing page image banner in README.md.

**Comment by Haimantika** [comment]
Hi @mschandana16 like I mentioned, we will soon be archiving this repo, as we no longer use it.
